title: Continuous Integration and Continuous Delivery Apps
description: The best apps for Continuous Integration and Continuous Delivery

baseurl: 'https://continuousintegration.io'
url: ''
port: 3000

twitter_username: CiCdApps
github_username:  boudewijnwolters
google_analytics:  'UA-85233914-1'

exclude:
    - 'node_modules'
    - 'sources'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'gulpfile.js'
    - 'package.json'

markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed