title: Site title

description: >
  Site description

baseurl: 'http://wp.pl'
url: ''
port: 3000

twitter_username: CiCdApps
github_username:  boudewijnwolters

exclude:
    - 'node_modules'
    - 'sources'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'gulpfile.js'
    - 'package.json'

markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed